# https://taskfile.dev

version: '3'

tasks:
  build:
    cmds:
    - go get -C . -d ./...
    - go build -C . -o ./bin
  build-r:
    cmds:
    - go get -C . -d ./...
    - go build -C . -o ./bin -ldflags "-s -w"
