name: Release

on:
  push:
    branches: [ "main" ]
    tags: [ "v.*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
          platforms: 'linux/amd64, darwin/amd64, windows/amd64'
          package: ''
          name: 'k-9'
          compress: 'false'
          dest: 'bin'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: k-9-${{ github.ref_name }}
          path: bin/k-9*

      - name: Release asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            bin/k-9*
          generate_release_notes: true
