name: Release

on:
  push:
    branches: [ "main" ]
    tags: [ "v.*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        uses: crazy-max/ghaction-xgo@v3
        with:
          xgo_version: latest
          go_version: 1.22
          dest: bin
          prefix: k-9
          targets: windows/amd64,linux/amd64,linux/arm64,darwin/arm64
          v: false
          x: true
          race: false
          ldflags: -s -w
          buildmode: default
          trimpath: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: k-9-${{ github.ref_name }}
          path: bin/k-9*

      - name: Release asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            bin/k-9*
          generate_release_notes: true
